"""Added note table

Revision ID: e22e1daaa799
Revises: 0c65e6abe469
Create Date: 2026-09-13 11:25:57.217944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22e1daaa799'
down_revision: Union[str, Sequence[str], None] = '0c65e6abe469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Note',
    sa.Column('note_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_pinned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('note_id', name=op.f('Note_pkey'))
    )
    op.create_table('note',
    sa.Column('note_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('note_id', name=op.f('note_pkey'))
    )
    op.create_index(op.f('ix_note_note'), 'note', ['note'], unique=False)
    op.create_index(op.f('ix_note_created_at'), 'note', ['created_at'], unique=False)
    op.drop_table('Task')
    # ### end Alembic commands ###
